/// Drift table definitions for journal entries.
///
/// Two tables: [JournalEntries] (header) and [JournalLines] (double-entry
/// ledger lines).  Both carry sync-metadata columns so the sync engine can
/// track state without a separate join.
library;

import 'package:drift/drift.dart';

// ── Journal entry header ──────────────────────────────────────────────────────

/// One row per manual, contra, or system journal entry created locally.
///
/// [localId] is stable throughout the entity's lifetime and is used for all
/// local FK relationships.  [remoteId] is populated after the first successful
/// push to the server.
class JournalEntries extends Table {
  // ── Stable identity ────────────────────────────────────────────────────────

  /// UUID v4 generated by [IdGenerator.newId] at creation time.
  TextColumn get localId => text()();

  /// Server UUID assigned after the entity has been synced.  `null` while
  /// the entry has never been successfully pushed.
  TextColumn get remoteId => text().nullable()();

  /// Tenant / company UUID.  All queries must be scoped to this value.
  TextColumn get companyId => text()();

  // ── Business fields ────────────────────────────────────────────────────────

  /// ISO 8601 date string, e.g. `'2026-07-27'`.
  TextColumn get entryDate => text()();

  /// Human-readable reference number (e.g. `'JNL-0001'`).
  ///
  /// Null while the remote server has not yet assigned a [NumberingSeries]
  /// value.  Shown in the UI as provisional until synced.
  TextColumn get referenceNumber => text().nullable()();

  TextColumn get description => text()();

  /// One of: `'MANUAL'`, `'CONTRA'`, `'JOURNAL_REVERSAL'`, `'YEAR_END'`,
  /// `'AUTO'` (system-generated by posting invoices etc.).
  TextColumn get sourceType => text().withDefault(const Constant('MANUAL'))();

  /// One of: `'draft'`, `'posted'`, `'reversed'`.
  /// See [JournalLifecycleStatus].
  TextColumn get lifecycleStatus =>
      text().withDefault(const Constant('draft'))();

  // ── Sync metadata ──────────────────────────────────────────────────────────

  /// Current [SyncStatus.name] for this entity.
  TextColumn get syncStatus =>
      text().withDefault(const Constant('localOnly'))();

  /// Incremented locally on every edit.  Used for version-based conflict
  /// detection.
  IntColumn get localRevision => integer().withDefault(const Constant(0))();

  /// Server-reported revision, populated after a successful pull.
  IntColumn get remoteRevision => integer().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  /// Soft-delete timestamp.  Records with a non-null [deletedAt] are hidden
  /// from normal queries but retained until the delete is synced.
  DateTimeColumn get deletedAt => dateTime().nullable()();

  /// When the entity was last successfully pushed to or pulled from the server.
  DateTimeColumn get lastSyncedAt => dateTime().nullable()();

  /// The last sync error message for display in the Sync Centre.
  TextColumn get syncError => text().nullable()();

  /// True when the local record has unsaved or un-synced changes.
  BoolColumn get isDirty => boolean().withDefault(const Constant(false))();

  /// Device UUID that created this entry (from [SecureDeviceId]).
  TextColumn get originDeviceId => text()();

  @override
  Set<Column> get primaryKey => {localId};
}

// ── Journal line (ledger entries) ─────────────────────────────────────────────

/// One row per debit or credit leg of a [JournalEntries] row.
///
/// Monetary amounts are stored as INTEGER paise (₹1 = 100 paise).
/// Use [Money.fromPaise] / [Money.toPaise] for all conversions.
///
/// **Never** store a `REAL` (double) for financial amounts.
class JournalLines extends Table {
  /// UUID v4 for this line.
  TextColumn get localId => text()();

  /// FK to [JournalEntries.localId].
  TextColumn get journalLocalId => text()();

  // ── Account reference ──────────────────────────────────────────────────────

  /// Server-side account UUID (always available because accounts come from the
  /// server chart-of-accounts seed and are pulled at first sync).
  TextColumn get accountId => text()();

  /// Human-readable code, e.g. `'1001'`.  Denormalised for fast display.
  TextColumn get accountCode => text()();

  /// Account name.  Denormalised for fast display.
  TextColumn get accountName => text()();

  // ── Entry ──────────────────────────────────────────────────────────────────

  /// `'DEBIT'` or `'CREDIT'`.
  TextColumn get direction => text()();

  /// Amount in paise (₹1 = 100).  Stored as INTEGER — never REAL.
  ///
  /// Convert with [Money.fromPaise] and [Money.toPaise].
  IntColumn get amountPaise => integer()();

  TextColumn get narration => text().nullable()();

  /// Display order within the journal entry.
  IntColumn get sortOrder => integer()();

  @override
  Set<Column> get primaryKey => {localId};
}
