/// Drift table definitions for the sync infrastructure.
///
/// Three tables:
/// - [SyncOperations]   — the transactional outbox of pending remote writes.
/// - [SyncConflicts]    — detected conflicts awaiting user resolution.
/// - [SyncCheckpoints]  — per-(company, entityType) pull cursors.
library;

import 'package:drift/drift.dart';

// ── Sync operations (outbox) ──────────────────────────────────────────────────

/// Every local write that requires a remote push inserts or updates a row here
/// inside the *same* SQLite transaction as the entity write.
///
/// The sync engine reads pending rows, sends them using the [idempotencyKey],
/// and updates the row on completion or failure.
class SyncOperations extends Table {
  /// UUID for this outbox entry.
  TextColumn get id => text()();

  /// Domain entity type, e.g. `'journal'`, `'invoice'`, `'expense'`.
  TextColumn get entityType => text()();

  /// [localId] of the entity to be synced.
  TextColumn get entityLocalId => text()();

  // ── Execution context (stored at queue time, never inferred from UI) ──────────

  /// Tenant / company UUID.  Required — every operation is company-scoped.
  /// The sync engine reads this from the operation, never from UI state.
  /// Default empty string for migration compatibility; real operations always
  /// supply a value.
  TextColumn get companyId => text().withDefault(const Constant(''))();

  /// Financial-year UUID.  Required for FY-dependent operations such as
  /// `journal.posted`.  Nullable for operations that don't cross FY
  /// boundaries (e.g. contact/account reference data pushes).
  TextColumn get financialYearId => text().nullable()();

  /// User UUID who queued the operation.
  /// Default empty string for migration compatibility.
  TextColumn get actorId => text().withDefault(const Constant(''))();

  /// Device UUID that created this operation.
  /// Default empty string for migration compatibility.
  TextColumn get deviceId => text().withDefault(const Constant(''))();

  /// What to do: `create`, `update`, `delete`, `post`, `reverse`,
  /// `finalize`, `send`, `reconcile`, `upload`.
  TextColumn get operationType => text()();

  /// JSON-encoded payload to send to the server.
  TextColumn get payload => text()();

  /// Stable idempotency key reused on every retry of this operation.
  ///
  /// Generated by [IdGenerator.createKey] / [IdGenerator.actionKey] and never
  /// changed after the operation is initially queued.
  TextColumn get idempotencyKey => text()();

  /// Scheduling priority — lower numbers are processed first.
  IntColumn get priority => integer().withDefault(const Constant(0))();

  /// Number of send attempts made so far.
  IntColumn get attemptCount => integer().withDefault(const Constant(0))();

  /// When the sync engine may next attempt this operation (UTC).
  ///
  /// `null` means "eligible immediately".
  DateTimeColumn get nextAttemptAt => dateTime().nullable()();

  DateTimeColumn get createdAt => dateTime()();

  /// When the sync engine last picked up this operation.
  DateTimeColumn get startedAt => dateTime().nullable()();

  /// When the operation completed successfully.
  DateTimeColumn get completedAt => dateTime().nullable()();

  /// The last error string, if any.
  TextColumn get lastError => text().nullable()();

  /// JSON array of [SyncOperations.id] values that must complete before this
  /// operation is eligible to run.
  ///
  /// Example: invoice send depends on invoice create/finalize.
  TextColumn get dependencyIds => text().nullable()();

  /// Current [SyncStatus.name] of this operation.
  TextColumn get status => text()();

  @override
  Set<Column> get primaryKey => {id};
}

// ── Sync conflicts ────────────────────────────────────────────────────────────

/// When both the local record and the server record have changed since the last
/// successful sync, the engine writes a row here instead of silently
/// overwriting either side.
///
/// The UI surfaces these to the user via the Sync Centre.
class SyncConflicts extends Table {
  TextColumn get id => text()();
  TextColumn get entityType => text()();
  TextColumn get entityLocalId => text()();

  /// JSON snapshot of the local version at conflict-detection time.
  TextColumn get localPayload => text()();

  /// JSON snapshot of the remote version at conflict-detection time.
  TextColumn get remotePayload => text()();

  DateTimeColumn get detectedAt => dateTime()();

  /// One of: `'kept_local'`, `'kept_remote'`, `'merged'`.
  TextColumn get resolution => text().nullable()();

  DateTimeColumn get resolvedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

// ── Sync checkpoints (pull cursors) ──────────────────────────────────────────

/// One row per (company, entityType) pair.  Stores the [lastServerSequence]
/// returned by the last successful pull so the next pull can request only newer
/// events from `GET /apexbooks/sync/pull?after=<lastServerSequence>`.
class SyncCheckpoints extends Table {
  TextColumn get companyId => text()();

  /// Entity type being tracked, e.g. `'journal'`, `'invoice'`, `'*'` (all).
  TextColumn get entityType => text()();

  /// The `server_sequence` of the last applied event.
  IntColumn get lastServerSequence =>
      integer().withDefault(const Constant(0))();

  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {companyId, entityType};
}
